apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactdeployment
  # namespace: flipkart
  labels:
    app: javawebapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      name: reactwebapppod1
      labels:
        app: reactapp
    spec:
      containers:
      - name: test
        image: singasanisuryateja/logiq:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: reactservice
  # namespace: flipkart
spec:
  type: NodePort
  selector:
    app: reactapp
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 32100
